### ISSUE TITLE
Unhandled exception on clicking a mapping after F3

### ISSUE THREAD

**Issue by IhateTrains** [ParadoxGameConverters/provinceMapper#20]
Steps to reproduce:

- load ImperatorToCK3 mappings
- click on the last mapping in the list ("-> Chaka, TIBET IMPASSABLE [...]")
- press F3 to create a new mapping, now it looks like this 
![image](https://user-images.githubusercontent.com/29546927/127036291-25f320e1-0455-49e8-907e-f5d2b8003993.png)
- click on the last mapping again ("-> Chaka, TIBET IMPASSABLE [...]")
- unhandled exception windows appears
![image](https://user-images.githubusercontent.com/29546927/127036463-0276f6f4-31db-4a5c-8c65-45f28107d899.png)

**Comment by Zemurin** [comment]
Fixed in #21
